---
# Copied from https://github.com/aws-samples/startup-kit-templates/blob/master/vpc.cfn.yml
AWSTemplateFormatVersion: 2010-09-09
Description: Contains database resources

Parameters:

  TemplateBucket:
    Type: String
    Description: The template bucket for the CloudFormation templates

  EnvironmentName:
    Type: String
    Description: Environment name - dev or prod
    Default: dev
    AllowedValues:
    - dev
    - integ1
    - staging
    - prod
    ConstraintDescription: Specify a valid environment name

  VpcStackName:
    Description: Name of an active CloudFormation stack that contains networking resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

  DatabaseStackName:
    Description: Name of an active CloudFormation stack that contains database resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

  DatabaseUser:
    Default: startupadmin
    Type: String
    Description: Database admin account name
    MinLength: 5
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DatabasePassword:
    NoEcho: true
    Type: String
    Description: Database admin account password
    MinLength: 6
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Password must contain only alphanumeric characters

Resources:

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/db.cfn.yml
      Parameters:
        NetworkStackName: !Ref VpcStackName
        EnvironmentName: !Ref EnvironmentName
        DatabaseEngine: postgres
        DatabaseInstanceClass: db.t2.micro
        DatabaseUser: !Ref DatabaseUser
        DatabasePassword: !Ref DatabasePassword
        EncryptionAtRest: false
        # Setting it to 5gb to save costs
        DatabaseSize: 5
        EnableAlarms: false
        EnhancedMonitoring: false

Outputs:

  RdsStackName:
    Value: !GetAtt RdsStack.Outputs.Name
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseStackName

